# Generated by Django 6.0.6 on 2026-06-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgsqTaskSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('slots', models.IntegerField()),
            ],
            options={
                'verbose_name': 'pgsq task slot',
                'verbose_name_plural': 'pgsq task slots',
                'db_table': 'pgsq_task_slot',
            },
        ),
        migrations.CreateModel(
            name='PgsqTask',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('func_path', models.CharField(help_text="Dotted module path to the task function, e.g. 'myapp.tasks.send_email'", max_length=512)),
                ('priority', models.IntegerField(default=0)),
                ('queue_name', models.CharField(default='default', max_length=255)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('takes_context', models.BooleanField(default=False)),
                ('backend_alias', models.CharField(default='default', max_length=255)),
                ('username', models.CharField(db_index=True, default='default', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('READY', 'READY'), ('RUNNING', 'RUNNING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], db_index=True, default='READY', max_length=20)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_time', models.DateTimeField(blank=True, db_index=True, help_text='Earliest time this task may be picked up again (exponential backoff).', null=True)),
                ('return_value', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
                ('worker_ids', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'pgsq task',
                'verbose_name_plural': 'pgsq tasks',
                'db_table': 'pgsq_task',
                'indexes': [models.Index(fields=['status', 'retry_time'], name='pgsq_task_status_4007ab_idx')],
            },
        ),
    ]
